kind: Service
apiVersion: v1
metadata:
  name:  mysql
spec:
  selector:
    app:  mysql
  type:  ClusterIP 
  ports:
  - name:  mysql
    port:  3306
    targetPort:  3306
--- 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        volumeMounts:
          - mountPath: /etc/mysql/conf.d
            name: mysql-config-map
        env: 
        # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
        - name: mysql-config-map
          configMap:
            name: mysql-configmap

          